### ISSUE TITLE
Curse message contains literal, unneeded new line

### ISSUE THREAD

**Issue by JoeDailey** [motocru/curse-bot#1]
https://github.com/motocru/curse-bot/blob/ea7cbd6b569040f513539fc427b41a01e8128ffd/bot.js#L187-L188

Template literals treat line breaks as literals. This results in a weirdly formatted message.

**Comment by motocru** [comment]
https://github.com/motocru/curse-bot/blob/34e206ac6755995927daef3d31d19f237efb7919/bot.js#L187

Line #188 concatenated to the end of line 187 to resolve odd spacing issue in commit: https://github.com/motocru/curse-bot/commit/34e206ac6755995927daef3d31d19f237efb7919

closing
