### ISSUE TITLE
Strings: Use Singular Grammar Correctly 

### ISSUE THREAD

**Issue by JoeDailey** [motocru/curse-bot#11]
This message is shown the most often:

> [This server has used {curse} over 1 times, {message}.](https://github.com/motocru/curse-bot/blob/6576bdcca7bb423742e58161872a73aa0a8c740f/bot.js#L315)

Its grammar is not correct. It should read, "This server has used {curse} for the first time..." bot.js should have some logic to account for the singular case.

**Comment by JoeDailey** [comment]
You might like to use *tagged template literals* for this... 
https://codeburst.io/javascript-es6-tagged-template-literals-a45c26e54761

**Comment by motocru** [comment]
Added an if statement to verify it the milestone made was equal to 1, then will go with the standard for all other messages.
https://github.com/motocru/curse-bot/blob/57ed51574c38e7c7b5bff90acd5f8f23b05f44ad/bot.js#L314-L320
Closing (I will look into tagged template literals though)
