### ISSUE TITLE
Wish: Reduce Noise by making 'first use' messages unique to the server (not the user)

### ISSUE THREAD

**Issue by JoeDailey** [motocru/curse-bot#2]
This is just a wish and not a bug. Feel free to close without action.

The current system will mention the (in)famous 'angel got it's wings' once per curse, per user. 

Proposed reduction: Only broadcast this once per curse. Do not broadcast this per user.

Proposed middle ground: Also broadcast the first time a user uses any curse. This would introduce them to the bot nicely!

**Comment by motocru** [comment]
Wish fulfilled, however, the messages were changed around a little. I didn't want to have the exact same message for the server's first time using a word vs. the user's first time cussing.

An if statement was added directly after determining the used text contained a curse to spit out a message if the swearobject for that user was empty
https://github.com/motocru/curse-bot/blob/1d6b766307e0b29e83a82e3c7240811bd7685a0f/bot.js#L97-L101

The first number specific curse milestone for users is now 10
https://github.com/motocru/curse-bot/blob/1d6b766307e0b29e83a82e3c7240811bd7685a0f/bot.js#L199-L200

serverMessages now checks if this was was the first time using a word for the whole server
https://github.com/motocru/curse-bot/blob/1d6b766307e0b29e83a82e3c7240811bd7685a0f/bot.js#L229-L230

closing
