### ISSUE TITLE
Repo Health: Include `curses.json`

### ISSUE THREAD

**Issue by JoeDailey** [motocru/curse-bot#5]
Without this file, I have no idea what the schema is. Information about this schema would be very helpful in working on this project or creating my own list.

Now, I know you do don't want to upload a couple megabytes of obscenities to Github. So find a way around it.

Something fun: Include a functional `curses.json`, but don't use any swear words. You could use words contrary to curses even... Please, thank you, love, friends, hug, bestie, etc.

It's up to you if you want to include an external link for the list *you* use.

**Comment by motocru** [comment]
Included another file in the root of the repository titled 'cursesSchema.json' that shows the schema of the curses.json file. contents of the file listed below. Closing

https://github.com/motocru/curse-bot/blob/72738c3f2a7548059f58a857c7c7a8efa7443dbb/cursesSchema.json#L1-L28
