### ISSUE TITLE
Code Quality: Remove massive switch casing

### ISSUE THREAD

**Issue by JoeDailey** [motocru/curse-bot#6]
Toward the end of bot.js there are two massive switch cases. Let's just talk about `messageDecider` for now, but this applies to `serverDecider` all the same. 

The readability of this code is very low because there is so much text. There are few ways to improve this. I am just going to talk about my favorite since it applies so well.

Right now your behavior *logic* and your content *definitions* are one in the same. You can easily make these two discrete ideas. Here's the why: *definitions* can be as longs as you need. I, the peer, can just trust that these are defined however you intended. *Logic*, on the other hand, needs to be short and expressive.

This may seem like high level gibberish, but bare with me. I'll *show* you what I mean.
```js
const MILESTONES = {
  10: curses.userMessages.message2,
  50: curses.userMessages.message3,
  100: curses.userMessages.message4,
  200: curses.userMessages.message5,
  250: curses.userMessages.message6,
  350: curses.userMessages.message7,
  500: curses.userMessages.message8,
  600: curses.userMessages.message9,
  700: curses.userMessages.message10,
  800: curses.userMessages.message11,
  1000: curses.userMessages.message12,
}
```
```js
function messageDecider(user, curse, cursesChanged) {
  const usesOfCurseByUser = user.jarObject[curse];
  const occurrencesOfCurseInNewMessage = cursesChanged[curse];

  const countBeforeNewMessage = usesOfCurseByUser - occurrencesOfCurseInNewMessage;

  for(const mile in MILESTONES) {
    if (countBeforeNewMessage < mile && usesOfCurseByUser >= mile) {
      return `<@!${user._id}> has used ${curse.toLowerCase()} over ${mile} times, ${MILESTONES[mile]}`;
    }
  }

  return null;
}
```

**Comment by motocru** [comment]
I will work to replace the massive switch casing. A new branch has been created on my local repo and will be pushed up when completed

**Comment by motocru** [comment]
there's a few things to go over so this comment might be a bit lengthy.

1. added constants containing the  numerical values and attached server messages from the curses.json file
https://github.com/motocru/curse-bot/blob/682fe73018673a9921d9cd5162a441a066475c48/bot.js#L7-L37

2. MessageEvaluator and ServerEvaluator now go to the exact same function of messageDecider. I may go back and turn the messageEvaluator and serverEvaluator into a single function but this was done in the interest of time
https://github.com/motocru/curse-bot/blob/682fe73018673a9921d9cd5162a441a066475c48/bot.js#L199-L220

3. Message Decider first determines if it was given a user object or if it was given a total object and then assigns values accordingly. messageDecider then goes through the suggested loop above and prints out the corresponding server or user message depending on what it received.
https://github.com/motocru/curse-bot/blob/682fe73018673a9921d9cd5162a441a066475c48/bot.js#L226-L243

Closing this issue
